### ISSUE TITLE
Choose different GnuTLS version or Ubuntu version?

### ISSUE THREAD

**Issue by tzz** [Silex/docker-emacs#1]
I can't figure out an easy way to switch to a different GnuTLS version as a package. Maybe it can only be done by switching the Ubuntu distribution? For example if I use Ubuntu 17.04 as the base, I can only install GnuTLS 3.5.6.

One alternative is to install GnuTLS from source, but I think the pre-built binaries are what most users will have.

Another way is to build Emacs in various Ubuntu and Debian releases. That might be hard to handle as a general facility, though it's useful for testing (so it might properly belong in a CI system).

If we don't allow any of these, I wonder if we can switch to 17.04 as the base, it's much more recent than 14.04.

**Comment by Silex** [comment]
Upgrading to some newer ubuntu sounds reasonable. I'll investigate.

Would 16.04 work for you? I prefer stable versions...

**Comment by tzz** [comment]
We can make a good case for stable and for latest; perhaps both should be available. In terms of security I feel latest is better.

**Comment by Silex** [comment]
Okay, 16.04 images are building at the moment.

**Comment by tzz** [comment]
Thank you.
