### ISSUE TITLE
the Dockerfiles in those subdirs aren't actually used

### ISSUE THREAD

**Issue by gonewest818** [Silex/docker-emacs#10]
The way `functions.sh` is written only the top level `Dockerfile` is used in the builds. Version-specific  scripts like `25.1/Dockerfile` are not consulted.  It doesn't matter right now because the Dockerfiles are currently identical, but I have a pull request underway for Emacs 23 where the base image and the build steps need to be different. So I need a way to separate them.

My plan is to rewrite `functions.sh` to launch `docker build -f Dockerfile.$tag` and then customize `Dockerfile.23` in the way I need.

**Comment by Silex** [comment]
> The way functions.sh is written only the top level Dockerfile is used in the builds. Version-specific scripts like 25.1/Dockerfile are not consulted.

Yes that was kinda intentional, because it greatly simplified the building process. These Dockerfiles exist only for the README and https://hub.docker.com/r/silex/emacs to be able to view them easily.

**Comment by gonewest818** [comment]
Understood. I had to directly link the Dockerfiles in the README because the GitHub doesn't follow the symlinks.  Are you opposed to the extra complexity?

**Comment by Silex** [comment]
No it looks fine, and would have been needed sooner or later. Let's continue in #11
