### ISSUE TITLE
Emacs 29.3 is out

### ISSUE THREAD

**Issue by agsdot** [Silex/docker-emacs#101]
https://www.reddit.com/r/emacs/comments/1bmuoku/emacs_293_released/

@Silex just a heads up, 29.3 was just released.

**Comment by agsdot** [comment]
https://lists.gnu.org/archive/html/emacs-devel/2024-03/msg00611.html

**Comment by Silex** [comment]
Thanks! images are building.

**Comment by agsdot** [comment]
No problem. Thanks for creating these docker images!
