### ISSUE TITLE
Emacs 26 can't install from ELPA

### ISSUE THREAD

**Issue by amake** [Silex/docker-emacs#104]
The signature check fails. Is this fixable?

```
% docker run --rm -it silex/emacs:26 emacs -Q --batch -l package --eval "(progn (package-initialize) (package-refresh-contents) (package-install 'transient))"
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Package refresh done
Setting `package-selected-packages' temporarily since "emacs -q" would overwrite customizations
Setting `package-selected-packages' temporarily since "emacs -q" would overwrite customizations
Failed to verify signature: "seq-2.24.tar.sig"
```

(Emacs 27+ all work fine.)

**Comment by Silex** [comment]
Ah interesting.

@purcell do you know about this? Since I just wrap https://github.com/purcell/nix-emacs-ci I think this issue will eventually move to your repo 😇

**Comment by purcell** [comment]
I had some inkling of this because I had to work around a CI setup that failed with this error: it's possible to set the var which stops `package.el` from verifying signatures.

Regarding the signature failure itself, I haven't dug into why it's happening but it's quite mysterious. Ultimately, even the older Emacsen produced by [nix-emacs-ci](https://github.com/purcell/nix-emacs-ci) are patched with the very latest ELPA package keyring (from Emacs HEAD), so this error _shouldn't_ be due to package signatures that were made with a private key not available to the Emacs 26 build. I'll dig into this if I can find some time, but I'm extremely time-limited currently.

**Comment by purcell** [comment]
With nix installed, it should be possible to do something like `nix run --accept-flake-config 'github:purcell/nix-emacs-ci#emacs-26-2' -- -Q` to start that Emacs locally, and then dig into what keyring is being used, or try manually installing that package etc.

**Comment by purcell** [comment]
When I fire up that Emacs version locally, and run the following it works:
```el
(progn
  (setq package-user-dir "/tmp/pkg-foo-2")
  (package-initialize)
  (package-refresh-contents)
  (package-install 'compat))
```
but I think that's because I have no `gpg` on my path, because `package.el` only enables `package-check-signature` when
```
(and (require 'epg-config) ('epg-find-configuration 'OpenPGP))
```

If I install `gpg` first, then I get the error we're seeing:
```
Debugger entered--Lisp error: (bad-signature "seq-2.24.tar.sig")
  signal(bad-signature ("seq-2.24.tar.sig"))
  package--check-signature-content("\211\001\263\004\0\001\n\0\035\026!\004\3043UGf\323\335\306B!\277$
  package--check-signature("https://elpa.gnu.org/packages/" "seq-2.24.tar" "seq-2.24/\0\0\0\0\0\0\0\0$
  package-install-from-archive(#s(package-desc :name seq :version (2 24) :summary "Sequence manipulat$
  mapc(package-install-from-archive (#s(package-desc :name seq :version (2 24) :summary "Sequence man$
  package-download-transaction((#s(package-desc :name seq :version (2 24) :summary "Sequence manipula$
  package-install(compat)
```
I then try to verify the signature separately in a terminal, using the keyring that came with that Emacs build (recall that I patch all builds to include the latest keyring):
```
curl https://elpa.gnu.org/packages/transient-0.7.4.tar.sig > /tmp/p; curl https://elpa.gnu.org/packages/transient-0.7.4.tar.sig > /tmp/p.sig; gpg --keyring /nix/store/02qx5sq3fqvlm0h2wm7xf5aabwqrmiq8-emacs-26-2/share/emacs/26.2/etc/package-keyring.gpg --verify /tmp/p.sig
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119  100   119    0     0    306      0 --:--:-- --:--:-- --:--:--   307
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119  100   119    0     0    290      0 --:--:-- --:--:-- --:--:--   290
gpg: assuming signed data in '/tmp/p'
gpg: Signature made Mon Aug  5 22:10:03 2024 IST
gpg:                using EDDSA key 0327BE68D64D9A1A66859F15645357D2883A0966
gpg: BAD signature from "GNU ELPA Signing Agent (2023) <elpasign@elpa.gnu.org>" [unknown]
```
Inspecting the contents of the bundled keyring:
```
gpg -k --keyring /nix/store/02qx5sq3fqvlm0h2wm7xf5aabwqrmiq8-emacs-26-2/share/emacs/26.2/etc/package-keyring.gpg
/nix/store/02qx5sq3fqvlm0h2wm7xf5aabwqrmiq8-emacs-26-2/share/emacs/26.2/etc/package-keyring.gpg
-----------------------------------------------------------------------------------------------
pub   rsa3072 2019-04-23 [SC] [expired: 2024-04-21]
      C433554766D3DDC64221BFAA066DAFCB81E42C40
uid           [ expired] GNU ELPA Signing Agent (2019) <elpasign@elpa.gnu.org>

pub   ed25519 2022-12-28 [C] [expires: 2032-12-25]
      AC49B8A5FDED6931F40EE78BF993C03786DE7ECA
uid           [ unknown] GNU ELPA Signing Agent (2023) <elpasign@elpa.gnu.org>
sub   ed25519 2022-12-28 [S] [expires: 2027-12-27]
```
These are the same contents as the latest in the [emacs repo here](https://github.com/emacsmirror/emacs/blob/master/etc/package-keyring.gpg), and in the [gnu-elpa-keyring-update package](https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html).

So overall I feel like GNU ELPA packages are actually getting signed by a private whose public counterpart is not distributed.

**Comment by Silex** [comment]
Nice finding! Should we report something to the Emacs mailing list / bugtracker ? My guess is that it's simpler to simply disable `package-check-signature` because it's unlikely there'll be a fix for Emacs 26.

**Comment by purcell** [comment]
What I don't understand yet is why it works with other Emacs versions. Do they just not decide to enable signature checking? Or do they check and find the signature accessible?!

**Comment by purcell** [comment]
The same test with Emacs 27.1 succeeds, and `package-check-signature` is enabled there, so it's not like it skipped the check. Quite mysterious. Its keyring is the same as above.

...

After a bit of googling, this looks like the issue: https://mail.gnu.org/archive/html/help-gnu-emacs/2024-06/msg00012.html

**Comment by purcell** [comment]
I'll try applying this change to older Emacsen: https://github.com/emacsmirror/emacs/commit/3c1967dbfe06b28ac074aee1e55a79bacfc36f8d.patch

**Comment by Silex** [comment]
Wonderful! Thanks a lot 👍

**Comment by purcell** [comment]
I haven't got the patch working with all Emacs versions yet, but will ping here once working.

**Comment by purcell** [comment]
Okay, that's merged now — it only affected Emacs 25.x and 26.x, in fact. Both 24.x and 27+ consider a package correctly signed if _at least one_ of its signatures is valid, whereas those problematic versions required _all of the signatures_ to be valid. I think the packages are still getting signed by several keys including a key that is obsolete/expired, so those particular versions rejected the corresponding signatures.

**Comment by Silex** [comment]
Thanks a lot Steve!

**Comment by purcell** [comment]
No worries, the mystery was annoying me too.

**Comment by amake** [comment]
Thanks so much for looking into this!

**Comment by Silex** [comment]
@amake: FYI I have a bit of trouble building images atm because of docker hub pull rate limits. It should be resolved within the week.

**Comment by amake** [comment]
Well it looks like you updated the `26` tag, and that works for me!
https://hub.docker.com/layers/silex/emacs/26/images/sha256-3bb725e3cb173162fd547bab17eb3df759224fa7dd111ac848fdaa8fef0bd669?context=explore

**Comment by Silex** [comment]
Right, 26.3 base image successfully went through:

https://github.com/Silex/docker-emacs/actions/runs/10344093788

The others will follow.

**Comment by purcell** [comment]
> because of docker hub pull rate limits

Apologies if you do this already, but you might consider pushing images to Github's container registry instead (or as well). Docker is getting increasingly limited.

**Comment by Silex** [comment]
I was considering it, but it looks like GHCR data limits are pretty low compared to docker hub:

https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages

It says 500 MB, but it looks like in practice this is never enforced 🤷 

Right now I'm exploring using a registry cache, which would solve the pull rate limits on docker hub.

But yeah maybe the simplest is to move to ghcr.io and be done with it, tho this will disrupt existing users of my images.

That or I build/push to ghcr.io AND then only push to docker hub.

**Comment by Silex** [comment]
For the record I use ghcr.io to build & cache images, then I push to docker hub. Seems to be sufficient to work around the hub limits for now.

**Comment by purcell** [comment]
Nice!
