### ISSUE TITLE
runtime images don't need the full compiler toolchain

### ISSUE THREAD

**Issue by gonewest818** [Silex/docker-emacs#13]
The size of all the compilers and so on appears to be more than 100MB, so I propose generating two builds, the current one and a 'slim" build, where the slim ones will need testing to make sure all the runtime dependencies are right. The "slim" images can be achieved with docker multi-stage builds.

**Comment by jgkamat** [comment]
FWIW, I personally found that ditching the compiled versions completely [and using pre-packaged emacs from various distros](https://github.com/jgkamat/airy-docker-emacs) instead was a lot better for my usecases.

**Comment by gonewest818** [comment]
I understand.  My use case is "continuous integration in environments where containers are supported."  I don't want to be debugging Emacs builds, but I also don't want to have any doubts how the packages are generated -- all the way down to the sources that went into the builds.

This set of build tooling is getting close to my ideal: a fully documented and repeatable set of Emacs builds that can be used in automated CI testing.

I don't care as much about the desktop interactive usage, although I will use them to run batch tests locally (ert-runner or buttercup, whatever).

**Comment by Silex** [comment]
That sounds good, maybe `-alpine` variants could also be worth doing.

I see that you have a PR brewing, so let's make the `-slim` variant first.

**Comment by gonewest818** [comment]
Agree. Alpine uses musl-libc, has its own dns resolver, busybox, etc.

**Comment by Silex** [comment]
Continuing in #18

**Comment by Silex** [comment]
@gonewest818, @jgkamat for information:

```
philippe@pv-desktop:~$ docker images | grep silex
silex/emacs     latest          b812328e7f61      44 minutes ago      1GB
silex/emacs     latest-slim     eb1edd47dcd0      31 minutes ago      534MB
silex/emacs     23              1e6b83a21d60      About an hour ago   710MB
silex/emacs     23-slim         565e6f79566c      44 minutes ago      325MB
silex/emacs     24              2a814ad40693      About an hour ago   983MB
silex/emacs     24-slim         5d94c27f0c04      35 minutes ago      531MB
```

I'll try to make `-alpine` images as well.
