### ISSUE TITLE
Reuse your images

### ISSUE THREAD

**Issue by DamienCassou** [Silex/docker-emacs#15]
follow up on https://github.com/rejeep/evm/issues/103.

Should we try to get your docker-emacs images reusable for other projects? What prevents us from using your images as is:

- they are built on a four-year old version of Ubuntu
- they require running with `/rootfs` which is probably not possible from gitlab
- cask requires python
- many scripts use Make to build

If you are interested I can send a PR. This will at least break your workflow regarding `/rootfs`.

**Comment by Silex** [comment]
> Should we try to get your docker-emacs images reusable for other projects?

Yes! :wink: 

> they are built on a four-year old version of Ubuntu

Well, Ubuntu 16.04 is two years old... For Emacs 23, we use 12.04 because it's where it builds the simplest.

What would you like us to use? Maybe you missed the recent changes.

> they require running with /rootfs which is probably not possible from gitlab

Oh, they don't *require* that. It's just an example to show how to access your / from within the container.

> cask requires python

We could add it to the requirements.

> many scripts use Make to build

I don't understand this point, can you elaborate?

> If you are interested I can send a PR. This will at least break your workflow regarding /rootfs.

Sure, otherwise just mention the changes you want and I'll do them.

**Comment by Silex** [comment]
About `/rootfs`, if you meant the `WORKDIR` instruction I think we can remove it, but I fail to really see how it can be a problem. It'd be nice if you have an example.

**Comment by DamienCassou** [comment]
> Well, Ubuntu 16.04 is two years old... For Emacs 23, we use 12.04 because it's where it builds the simplest.

Sorry. When going to https://hub.docker.com/r/silex/emacs/~/dockerfile/ I see 14.04. Your github project seems to reference 16.04 though. I don't understand the web interface for docker.

> What would you like us to use?

16.04 (latest LTS) is fine.

> Oh, they don't require [running with /rootfs]. It's just an example to show how to access your / from within the container.

I though the `workdir` instruction at the end would be problematic. It might not be :-).

>> many scripts use Make to build
> I don't understand this point, can you elaborate?

just that installing `make` would be nice :-).

**Comment by Silex** [comment]
>> Well, Ubuntu 16.04 is two years old... For Emacs 23, we use 12.04 because it's where it builds the simplest.
>
> Sorry. When going to https://hub.docker.com/r/silex/emacs/~/dockerfile/ I see 14.04. Your github project seems to reference 16.04 though. I don't understand the web interface for docker.

Ah right, that is indeed a problem. I'll see if I can make it so the hub picks up the new Dockerfile. Thanks for making me notice!

> just that installing make would be nice :-).

Well it's already installed :innocent: 

``` shell
$ docker run -it --rm --entrypoint="make" silex/emacs:latest -v
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by DamienCassou** [comment]
I guess issue #20 prevents us from using your Docker images for now.

**Comment by Silex** [comment]
@DamienCassou: anything else needs to be done or can we close this?

**Comment by DamienCassou** [comment]
Please close it. I will reopen if needed.

**Comment by Silex** [comment]
Alright. For information there are now `-slim` images, I didn't update the README yet.
