### ISSUE TITLE
Dockerfile listed in hub.docker.com is out of date

### ISSUE THREAD

**Issue by Silex** [Silex/docker-emacs#16]
I think the only way to fix that is to trigger a build, with a Dockerfile present at the root directory.

Need to investigate.

**Comment by Silex** [comment]
@gonewest818: you went the symlink way, but are you opposed to having duplicate files in subdirectories like before your PR?

I understand the symlink way "makes sense", but the standard practice is https://hub.docker.com/_/ruby/ with duplicates, like https://github.com/docker-library/ruby/blob/83c60cc26a1efb0ea581b3343a97df7508481fcf/2.4/stretch/Dockerfile

Then there's a script that generates these automatically, based on templates... maybe we don't need to go that far tho.

**Comment by gonewest818** [comment]
You could say the symlinks are a substitute for a build template, either one would eliminate the duplication and either one documents how the different builds are similar. 

Thinking about the in-progress “slim” work. I’ve done numerous experimental changes to get that working the way I intend. It would have been quite frustrating if I had to manually copy files into 6-7 directories for each change.

For those projects that literally use a template engine to construct their Dockerfiles dynamically, how do they solve the documentation links? The cases I’ve seen they just refer to the github repo as a whole and leave it to the reader to deduce how the build pieces things together. I think these symlinks are considerably more informative.

**Comment by Silex** [comment]
From what I've seen, all the official repo use something like https://github.com/docker-library/ruby/tree/6bccf4bd0c6aa158b4a842c29f78c335ec9dc41b

See the templates, and the generator script. My guess is that they have some CI that when you modify the templates, it generates the Dockerfiles and then commits them automagically.

The documentation at https://hub.docker.com/r/library/ruby/ then simply links to the fully generated dockerfile instead of the template. For example our template only contains `GIT_BRANCH` and you have to trust that the build used the correct value when building.

> It would have been quite frustrating if I had to manually copy files into 6-7 directories for each change.

I understand, at the same time it's not something we do often.

I'll probably keep the symlinks for now, but I'm still considering using some kind of generator script.

**Comment by gonewest818** [comment]
If you do adopt a generator script, my preference is NOT just running  `sed` over a legitimate Dockerfile to replace initial values with new values (because we have `--build-args` for that now). I would do it only if you need something besides simple substitution.

**Comment by Silex** [comment]
Right, well let's keep it as it is for now.

I will still need to push a Dockerfile at the root of the repository so https://docs.docker.com/docker-hub/builds/#understand-the-build-process can use it and update the Dockerfile listed on the hub.

I might submit a "dummy" one that only contains something like:

"This build is automated using travis-ci because we cannot build emacs in a container (see issue bla bla). Check http://link_to_real_dockerfile"

Then trigger that build once and immediatly trigger the travis-ci so the "master" image is not wrong for too long.

I expect that I need to let the build succeed in order for the Dockerfile replacement to happen. Maybe I could trigger it on a "deleteme" tag instead and delete the tag afterwards. That or maybe I create a `update-hub` branch with the Dockerfile and build that instead. That'd work, I'll give it a go.

**Comment by gonewest818** [comment]
It's frustrating that you can't just delete the Dockerfile from hub.

e.g. Mesos (https://hub.docker.com/r/mesosphere/mesos/) doesn't have a Dockerfile link at all.

**Comment by Silex** [comment]
Well, it's because it is not an automated repository.

One solution could be to delete the repository and re-create it as not automated.

I wanted it to display "Automated repository" because it's what it was originally, until Emacs didn't build inside containers in recent versions. Myself as a user also much prefer automated repositories because it means they stay up to date when the base image changes.

I understand it's kinda a lie because the automation is not through the hub but through travis-ci. Maybe I could simply switch to a normal repository but mention in the README that everything is automated in travis-ci.

**Comment by Silex** [comment]
Fixed by pushign & building a `update-docker-hub` branch that contains a dummy Dockerfile and triggering a build.
