### ISSUE TITLE
Allow contributors to push to their hub.docker.com from a feature branch

### ISSUE THREAD

**Issue by gonewest818** [Silex/docker-emacs#19]
As a contributor I'm working in a clone of this repo and in a feature branch (i.e. not "master"). Which means for every new feature I'm developing, the first thing I have to do is push a commit that disables the `[ "$current_branch" == "master" ]` type logic that prevents my CI tests from pushing, then do my work and check the results in `hub.docker.com/u/gonewest818`, then rebase and remove my commit that allows me to push from a feature branch, and then submit the PR.

It would be nice if I could override that push logic without an extra commit. A switch or flag, perhaps an environment variable I can set in my Travis CI settings (but you would never set in yours).

**Comment by Silex** [comment]
Ah, interesting you'd want it to push to your images no matter what? Personally I'd only want master to be pushed, that or some $branch prefix for the image name.

Anyway I need to think about it, but I'm not opposed to the idea :+1:

**Comment by gonewest818** [comment]
It should be limited to the case where `$TRAVIS_REPO_SLUG != "Silex/docker-emacs"` and then like you say, it could be based on the feature branch having a certain prefix. Definitely doesn't need to be "no matter what".

**Comment by Silex** [comment]
Well my use case is: only push the images when something is pushed to master on the `Silex/docker-emacs` repository. That way I don't push when testing out branches or receive PRs.

What would be your use case?

**Comment by gonewest818** [comment]
I just mean both your case and mine:
```
  if [ -z "$DOCKER_USERNAME" ] || [ "$TRAVIS_PULL_REQUEST" == "true" ] || \
     ( [ "$TRAVIS_REPO_SLUG" == "Silex/docker-emacs" ] && [ "$current_branch" != "master" ] ) || \
     ( [ "$TRAVIS_REPO_SLUG" != "Silex/docker-emacs" ] && ! [ "$current_branch" =~ <insert-a-regexp-here> ] ); then
    echo Not pushing
  else ...
```

That `<insert-a-regexp-here>` can be whatever you like. I just need a way to push builds to my dockerhub account when I'm testing in my fork.

**Comment by Silex** [comment]
Would something like `$current_branch =~ /(master|staging-.*)/` be ok?

That way, there's no test for `Silex/docker-emacs` at all. And all the forks (and me) can use `staging-` or `master` to push.

**Comment by gonewest818** [comment]
Yes, thanks.

**Comment by Silex** [comment]
Fixed by https://github.com/Silex/docker-emacs/commit/61054617003dc28256f27de643f3c95d135870ca. Please reopen if there's a problem.

**Comment by gonewest818** [comment]
Thank you
