### ISSUE TITLE
Master build fails on Docker 17.06 on Mac OS X

### ISSUE THREAD

**Issue by tzz** [Silex/docker-emacs#2]
Emacs fails to compile master in the bootstrap stage, I'm not sure why. This is Docker 17.06 on Mac OS X:

```
Dumping under the name emacs
**************************************************
Warning: Your system has a gap between BSS and the
heap (13182431 bytes).  This usually means that exec-shield
or something similar is in effect.  The dump may
fail because of this.  See the section about
exec-shield in etc/PROBLEMS for more information.
**************************************************
make[1]: *** [bootstrap-emacs] Segmentation fault
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....
```

I get the error with a base Ubuntu image of 14.04 and 17.04, so maybe it's specific to Mac OS X?

I can run the built `silex/emacs` images so it must work for other people...

**Comment by Silex** [comment]
No it's normal, Emacs cannot build inside Docker at the moment.

See https://github.com/moby/moby/issues/22801

I'm building silex/emacs inside travis-ci with special tricks.

**Comment by tzz** [comment]
@Silex can you share the tricks please? I can't figure them out from your Travis build. I'd love to build on 17.04 and with custom extensions. Thank you.

**Comment by tzz** [comment]
Reading that thread, it looks like it requires an older Docker daemon and Travis happens to provide that. Ugh.

**Comment by Silex** [comment]
Yes exactly travis uses an old docker which is not subject to the problem. If you want to build locally, do this:

``` bash
OLD_VAL=$(cat /proc/sys/kernel/randomize_va_space)
echo 0 > /proc/sys/kernel/randomize_va_space
docker build bla bla
echo $OLD_VAL > /proc/sys/kernel/randomize_va_space
```

Basically just disable the bits that prevents Emacs from building.

**Comment by tzz** [comment]
That's hilarious. Well, it will work well enough for my purposes (described in #1 )

Thank you so much for your help!

**Comment by Silex** [comment]
You're welcome :wink:
