### ISSUE TITLE
Standard input is not a tty

### ISSUE THREAD

**Issue by DamienCassou** [Silex/docker-emacs#20]
Hi,

trying to use your images with our gitlab CI [shows this problem](https://gitlab.petton.fr/mpdel/libmpdel/-/jobs/1755):

```
Running with gitlab-runner 10.5.0 (80b03db9)
  on luz4-libmpdel 562a0aa1
Using Docker executor with image silex/emacs:26.0 ...
Pulling docker image silex/emacs:26.0 ...
Using docker image sha256:7dea48171626a2d4875d51b5a3fd64d604a0c555c839ffda86d42540882af222 for silex/emacs:26.0 ...
Running on runner-562a0aa1-project-70-concurrent-0 via luz4...
Cloning repository...
Cloning into '/builds/mpdel/libmpdel'...
Checking out 3b6d9ede as test-new-evm-builds...
Skipping Git submodules setup
emacs: standard input is not a tty
emacs: standard input is not a tty
ERROR: Job failed: exit code 1
```

I guess this is because gitlab tries to execute the Dockerfile's `entrypoint` (which is the Emacs binary). Is that needed?

**Comment by Silex** [comment]
Just change the entrypoint to whatever you need?

`docker run -it --rm --entrypoint=bash silex/emacs:latest`

Anyway, we can also remove the `ENTRYPOINT`, but given this change could maybe break some workflows I'll make an issue out of it.

**Comment by Silex** [comment]
Fixed by #21

**Comment by rzr** [comment]
Hi, I came to this error while searching for "emacs: standard input is not a tty" and "docker" , I am wondering how can emacs be used to build docker image, any hints ? sorry for noise

**Comment by Silex** [comment]
@rzr: this error appens because you forgot to add `-t`:

```
philippe@pv-desktop:~$ docker run -i --rm silex/emacs
emacs: standard input is not a tty

philippe@pv-desktop:~$ docker run -it --rm silex/emacs
(emacs works fine)
```

Your question is not really clear, can you ask again with more details?
