### ISSUE TITLE
Remove ENTRYPOINT from the Dockerfile

### ISSUE THREAD

**Issue by Silex** [Silex/docker-emacs#21]
@gonewest818, @jgkamat: would you be ok with removing the entrypoint and not specifying `ENTRYPOINT` or `CMD` at all? this means `CMD` would be `bash` by default.

See #20 for more information.

Other users of these images please voice your opinions :smile:

**Comment by gonewest818** [comment]
Doesn't matter to me. CircleCI allows ENTRYPOINT and CMD to be set or overridden in `.circleci/config.yml`.

https://github.com/gonewest818/adafruit-wisdom.el/blob/master/.circleci/config.yml#L15-L16

**Comment by Silex** [comment]
@DamienCassou: forgot to summon you here :smile: 

Anyway, I'm not against removing the `ENTRYPOINT` if it makes sense, but I think most people expect that when you run the image without arguments Emacs is being run.

The idea with the entry point is that it allows things like this:

`docker run -it --rm silex/emacs:latest /rootfs/foo` and you are editing the file foo.

We could also achieve that with `CMD`, but then if you want to pass additional args you need to specify emacs on the command line like this:

`docker run -it --rm silex/emacs:latest emacs /rootfs/foo`

**Comment by DamienCassou** [comment]
Do whatever suits you best. I will adapt :-).

**Comment by Silex** [comment]
Okay, python/ruby etc simply use `CMD python` so I'll follow their lead.

I'll push a commit that sets `CMD` to emacs.

**Comment by Silex** [comment]
Changed in 0c73a0429a1c2fca1b5c1bf302e285ae6a6fce55

Given this image can also be used to test other Emacs related tasks, it makes sense to make it easy for users to be able to change the command.
