### ISSUE TITLE
Build Alpine images

### ISSUE THREAD

**Issue by gonewest818** [Silex/docker-emacs#22]
Found the build script for the alpine package. It includes the clues you would need to write a dockerfile.

https://git.alpinelinux.org/cgit/aports/tree/community/emacs/APKBUILD?id=5187af9c25cb4a04276ce1a6a7c84ded34161c6a

**Comment by Silex** [comment]
Thanks! :+1:

**Comment by Silex** [comment]
Okay the refactor is in progress, which should allow to add alpine images.

**Comment by Silex** [comment]
@jgkamat, @gonewest818 

little teaser:

``` shell
silex/emacs     25.3-alpine         68a41ecb1e25      8 seconds ago        197MB
silex/emacs     25.3-alpine-cask    0af9f9f12498      About a minute ago   236MB
```

So, alpine version will come soon, but I need to refactor even more as I need to patch the Emacs source in order for it to build.

We see that cask needs an additional ~40MB, mostly because of python.

**Comment by Silex** [comment]
Okay, just a bit of warning: I'll only be able to generate alpine images starting with `25.1` (that means 25.2, 25.3, 26.0, master, etc)

The patches are not backward compatible with `24.5`, I tried to backport them but that failed miserably.

For `26.0` and `master` I had to adapt the patches a bit.

**Comment by Silex** [comment]
Okay, `25.1` segfaults when I try to build it. I'll just remove it from the alpine images for now.

**Comment by Silex** [comment]
Need to wait 2-3 hours before the images are built & pushed on the docker hub.
