### ISSUE TITLE
New approach

### ISSUE THREAD

**Issue by DamienCassou** [Silex/docker-emacs#23]
Hi,

I just wanted to let you know I have started a completely new approach to do the same as you: https://gitlab.com/DamienCassou/emacs-ci-docker. The differences between approaches are, in my opinion:

- because I'm using gitlab docker's registry, I believe deployment is simpler (the .gitlab-ci.yml takes care of everything automatically)
- my repository contains only 4 files
- you have some tags (e.g., `master` and `latest`) that I didn't care implement (yet)
- I don't build `master` or Emacs 23

What do you think?

**Comment by Silex** [comment]
Building from the tarballs is how this repository used to work (https://github.com/Silex/docker-emacs/commit/c3d648b7c302896243cc6dfb3a5341cb57babc9a), but because I wanted to build pre-test images and `master` I had to use git, and thus used git for all the other versions.

The only difference seems to be about the gitlab docker's registry, which probably makes it simpler if your jobs already run on gitlab.

My primary goal is to build images for docker's hub. Maybe I'll switch to gitlab one day if it happens to be better/simpler, back in the days travis was better.

**Comment by gonewest818** [comment]
It’s interesting that they let you change kernel settings via the proc filesystem when running docker in docker. It’s like your CI job is running privileged which, AFAIK, shouldn’t be allowed in a multitenant service like gitlab.

**Comment by Silex** [comment]
> It’s interesting that they let you change kernel settings via the proc filesystem when running docker in docker.

Maybe it's already disabled, like on travis?

**Comment by gonewest818** [comment]
No idea, I would have expected permissions to prevent the Gitlab job from doing “echo 1 > /proc/whatever”

**Comment by Silex** [comment]
Right, when I try locally it says "read only filesystem".

**Comment by DamienCassou** [comment]
> Maybe it's already disabled, like on travis?

it's not. Without this line, the job crashes

**Comment by Silex** [comment]
@DamienCassou: hum, btw are you expecting something from this issue? Can we close it?

**Comment by DamienCassou** [comment]
You can surely close the ticket. I was just presenting an alternative solution in case you are interested.

**Comment by DamienCassou** [comment]
f

**Comment by Silex** [comment]
@DamienCassou: btw, your images are constantly rebuilt no? Or does it avoid rebuilds because of the gitlab-ci registry integration?

**Comment by DamienCassou** [comment]
Philippe Vaucher <notifications@github.com> writes:
> @DamienCassou: btw, your images are constantly rebuilt no? Or does it
> avoid rebuilds because of the gitlab-ci registry integration?

I'm not sure I understand the question. The images are rebuilt each time
I push a commit to the master branch of the repository. Do you see any
problem with this approach? What do you expect?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Silex** [comment]
Well, I expect the images:

1. to be rebuilt when the base image changes
1. to not rebuild if there is no need

Based on your answer I guess you have neither feature, but it's probably not a concern in your case.

FYI we achieve 1. with a cron job that runs daily and 2. by copying the emacs source into the image so the caching mechanism can trigger, along with some flags.
