### ISSUE TITLE
magit requires git >= 1.9.4

### ISSUE THREAD

**Issue by tesujimath** [Silex/docker-emacs#3]
Thanks for this container, it's a great way to run current emacs on e.g. CentOS.  I need current emacs for magit.  However, current magit requires git >= 1.9.4.

```
Error (magit): Magit requires Git >= 1.9.4, you are using 1.9.1.
```

Any chance of an update to this container with such a git?

**Comment by jgkamat** [comment]
Right now this builds with `from ubuntu:14.04`

Maybe it can be changed to `from debian:9` so the resulting docker image is smaller and so it has newer dependencies?

**Comment by tesujimath** [comment]
Looks like Ubuntu 16.04 LTS has git 2.7.4, which would also be fine.

**Comment by Silex** [comment]
Yes, I plan to upgrade the base image as discussed in #1.

16.04 is my current candidate, I'll see what I can do today :-)

**Comment by Silex** [comment]
Alright, it's building and there should be new images in ~3h.

**Comment by tesujimath** [comment]
Thanks, the new image is great, magit problem solved.
