### ISSUE TITLE
ssh for tramp

### ISSUE THREAD

**Issue by ghost** [Silex/docker-emacs#30]
These are great!  Thanks for creating these!

BTW, without SSH, tramp in emacs is useless.  :)

**Comment by jgkamat** [comment]
Tramp can probably be used without SSH (over different backends that don't depend on ssh) but this would be nice to have.

SSH might be in the dev images already, did you give those a try?

On June 2, 2018 6:03:21 PM EDT, matt812 <notifications@github.com> wrote:
>These are great!  Thanks for creating these!
>
>BTW, without SSH, tramp in emacs is useless.  :)

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Silex** [comment]
Thanks! Well, `ssh` is indeed present in the dev images. I'll compute how much it adds to the standard images, if that's less than 10 MB I think I'll go ahead and add it.

**Comment by Silex** [comment]
This should be fixed by 79dfb38612f969bc5366911b7c7a05370245f914, give a bit of time for the images to build.

**Comment by ghost** [comment]
Thanks!  👍
