### ISSUE TITLE
Always downloading new images

### ISSUE THREAD

**Issue by DamienCassou** [Silex/docker-emacs#32]
For a couple of days, CI jobs have been re-downloading new images very often, changing build time from 6 seconds to 6 minutes.

**Comment by Silex** [comment]
Argh! This is because ee8d9e09e871d71f899944079b8ac61b76681bcd does not work as I thought it would.

I'm currently fixing this, will keep you updated... In a near future, #31 will fix this once for good.

Sorry for the annoyance & thanks for reporting.

**Comment by Silex** [comment]
Alright, this should be fixed and your next ci-job will also be 6 min, but the next one should be 6 seconds.

**Comment by DamienCassou** [comment]
Philippe Vaucher <notifications@github.com> writes:
> Argh! This is because ee8d9e09e871d71f899944079b8ac61b76681bcd does
> not work as I thought it would.  I'm currently fixing this, will keep
> you updated.  Sorry for the annoyance & thanks for reporting.


Nothing to be sorry about. I like your docker images very much. I
migrate all my projects to them :-).

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Silex** [comment]
> Nothing to be sorry about. I like your docker images very much. I
> migrate all my projects to them :-)

Thanks! :+1:
