### ISSUE TITLE
Add GnuPG 2

### ISSUE THREAD

**Issue by tzz** [Silex/docker-emacs#35]
The installed version of GnuPG doesn't work with EPA/EPG (no `--pinentry-mode` option) which makes it challenging to use `authinfo.gpg` etc. from inside the image.

**Comment by Silex** [comment]
Would ubuntu 18.04 really fix the problem? If 18.04 does not work for some reason, how do we fix it in 16.04?

**Comment by tzz** [comment]
I'm not suggesting Ubuntu 18.04 would fix this. It's separate from #34 .

**Comment by Silex** [comment]
Please test again with the new images.

**Comment by Silex** [comment]
@tzz: ping

**Comment by Silex** [comment]
@tzz: ping

**Comment by Silex** [comment]
Fixed by 8131b2a98692b2f896a3472ba46bb445e5523955

**Comment by tzz** [comment]
Sorry for the late response @Silex . I was on a work trip and just got back today. Thank you for working on this!

**Comment by tzz** [comment]
I can confirm that GnuPG 2.x is installed and it works well with Emacs (EPA/EPG and auth-source).

In case it helps anyone, here's how you can run it so the gpg-agent and X are forwarded:

```console
% docker run -it --rm -v /:/rootfs -e GPG_AGENT_INFO=$GPG_AGENT_INFO \
      -e DISPLAY=$DISPLAY -v /run/user/$(id -u):/run/user/$(id -u) \
      -v /tmp/.X11-unix:/tmp/.X11-unix silex/emacs:master-dev
```
