### ISSUE TITLE
SSH daemon for convenience

### ISSUE THREAD

**Issue by tzz** [Silex/docker-emacs#36]
Often it's useful to simply SSH into this container and run Emacs. For that purpose, one would run `docker run ...... -p 5202:22 sshd -D` on the host machine and then SSH into that daemon, running Emacs.

This is particularly useful when the user is coming from non-Linux remote machines (Windows in particular) running a X server that needs to be forwarded over SSH (Putty/plink) through firewalls and bastion hosts.

Is there any way the option to run a SSH daemon could be available? Maybe by just installing `openssh-server` and letting the user run it themselves?

**Comment by Silex** [comment]
Hum, if you want to run something in the container why not simply use `docker exec`? with the `-it` flags you can even run bash and basically do whatever else you need to do along Emacs.

**Comment by tzz** [comment]
Passing the SSH agent and a X connection through `docker exec` is not easy and requires local access to the machine. I tried with `xauth` and passing connections but it's really complicated compared to simply doing SSH into the container. From a Windows machine it's particularly hard.

**Comment by Silex** [comment]
My point was more along the lines of:

`docker exec -it CONTAINER bash -c 'apt update && apt install openssh-server'`

Then configure it, etc.

**Comment by tzz** [comment]
That's what I do right now, except I `docker build` locally. Unfortunately in my environment it's really hard to add software to the image because of restrictive firewalls and Docker and infosec policies.

In any case, this was just a suggestion. I can keep doing the SSH server install on my side. I just thought other users might find this useful, especially if they have similarly restrictive policies around software installs. Feel free to close if you think it's better left to the end user.

**Comment by Silex** [comment]
"Installing SSH in the container" has quite a history of being a bad docker practice, and thus I think it's a bad idea to do it here... even if I understand that what you're doing is a bit different.

I think your usecase is really not common, but if enough people want this feature maybe I'll change my mind. In the meantime I'll close this, feel free to refer people to this issue so they voice their opinion.

**Comment by tzz** [comment]
Absolutely, and thank you for considering it. This is a terrific project and has helped me significantly to streamline my Emacs usage.
