### ISSUE TITLE
Emacs-22 image

### ISSUE THREAD

**Issue by conao3** [Silex/docker-emacs#41]
macOS still bundles Emacs-22.1. I want to use it in docker.
But below Dockerfile produce `make` error.
```dockerfile
FROM ubuntu:12.04 as dev

RUN apt-get update
RUN apt-get install -y build-essential

RUN apt-get install -y libncurses-dev

RUN apt-get install -y git
RUN apt-get install -y autoconf
RUN apt-get install -y automake
RUN apt-get install -y curl
RUN apt-get install -y gnupg
RUN apt-get install -y openssh-client
RUN apt-get install -y texinfo
RUN apt-get install -y libgnutls-dev

RUN apt-get install -y libdbus-1-dev

RUN rm -rf /var/lib/apt/lists/*

ENV EMACS_BRANCH="emacs-23.4"
ENV EMACS_VERSION="23.4"

WORKDIR /opt
RUN curl -vLO https://ftp.gnu.org/pub/gnu/emacs/emacs-22.3.tar.gz
RUN tar xf emacs-22.3.tar.gz
RUN mv -v emacs-22.3 emacs

RUN cd /opt/emacs && \
    ./configure --with-crt-dir=/usr/lib/x86_64-linux-gnu && \
    make bootstrap && \
    make install

CMD ["emacs"]
```

```
Configured for `x86_64-unknown-linux-gnu'.

  Where should the build process find the source code?    /opt/emacs
  What operating system and machine description files should Emacs use?
        `s/gnu-linux.h' and `m/amdx86-64.h'
  What compiler should emacs be built with?               gcc -g -O2 -Wno-pointer-sign
  Should Emacs use the GNU version of malloc?             yes
      (Using Doug Lea's new malloc from the GNU C Library.)
  Should Emacs use a relocating allocator for buffers?    yes
  Should Emacs use mmap(2) for buffer allocation?         no
  What window system should Emacs use?                    none
  What toolkit should Emacs use?                          none
  Where do we find X Windows header files?                NONE
  Where do we find X Windows libraries?                   NONE
  Does Emacs use -lXaw3d?                                 no
  Does Emacs use -lXpm?                                   no
  Does Emacs use -ljpeg?                                  no
  Does Emacs use -ltiff?                                  no
  Does Emacs use -lungif?                                 no
  Does Emacs use -lpng?                                   no
  Does Emacs use X toolkit scroll bars?                   no

configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib-src/Makefile.c
config.status: creating oldXMenu/Makefile
config.status: creating man/Makefile
config.status: creating lwlib/Makefile
config.status: creating src/Makefile.c
config.status: creating lisp/Makefile
config.status: creating lispref/Makefile
config.status: creating lispintro/Makefile
config.status: creating leim/Makefile
config.status: creating src/config.h
config.status: executing default commands
creating src/epaths.h
creating lib-src/Makefile
creating src/Makefile
(cd src;      make  mostlyclean)
make[1]: Entering directory `/opt/emacs/src'
make[1]: Leaving directory `/opt/emacs/src'
Makefile:82: *** commands commence before first target.  Stop.
make: *** [bootstrap-clean-before-fast] Error 2
The command '/bin/sh -c cd /opt/emacs &&     ./configure --with-crt-dir=/usr/lib/x86_64-linux-gnu &&     make bootstrap &&     make install' returned a non-zero code: 2
```
Have you try build Emacs-22 on docker ubuntu 12.04?

**Comment by Silex** [comment]
Hello,

In #37 we found that Emacs `23.2` and downwards do not build because of https://debbugs.gnu.org/cgi/bugreport.cgi?bug=5857.

Theorically it'd be possible to patch the source in order for it to build, but why bother for such old images? Why exactly do you want `22.1`?

**Comment by conao3** [comment]
Hello,

I develop Emacs package (such as [leaf.el](https://github.com/conao3/leaf.el), [cort-test.el](https://github.com/conao3/cort-test.el),,,) working on Emacs-22 or above to be able to working in various environments (i.e. old university workstation,,,).

Until now I am using Emacs-22 bundled with macOS (/usr/bin/emacs) and Emacs builded from source (Emacs-23, 24, 25, 26), but I am planning to move to a test environment using Docker image.

**Comment by conao3** [comment]
I think that there is room for discussion on how far old Emacs will be supported.
But my college workstations and macOS bundle Emacs-22.1, so some of the packages I develop are guaranteed to work properly from Emacs-22.1.

**Comment by Silex** [comment]
Well, here is the list of all "old" versions not currently being built: 22.1, 22.2, 22.3, 23.1, 23.2b, 23.3b

Do you think we should build them all? If no, which one should we leave out?

We can probably backport the patch for 23.3 or write some equivalent in order to build old images, but I'm a bit on the fence... mainly because `22.1` is such an old version that it feels backward to support it.

If you look at other images like https://hub.docker.com/_/ruby, old versions are not supported, so I would tend to follow this policy. But as I said I'm on the fence, and we could maybe build them in another repository of old images, or list them differently, or we simply add them and try to support as much versions as possible, etc.

**Comment by conao3** [comment]
It is together with the result I tried.
It is depends on you to finally decide how much to support the version (because it was not possible with my skill...), but if I can use Emacs from 22.1 on docker, I feel happy.

**Comment by Silex** [comment]
Okay I tried to build the old images but it's just too much work.

Here is my attempt:

https://github.com/Silex/docker-emacs/commit/32e8860ac07d9733d7cc22996582ca298c223fdf
https://travis-ci.org/Silex/docker-emacs/builds/499242031

I already patched the `unix` macro bug then found another bug with invalid makefiles generation, and now it fails at:

```
make[2]: *** No rule to make target `/usr/lib/crt1.o', needed by `temacs'.  Stop.
```

You can play with the https://github.com/Silex/docker-emacs/tree/build-old-images branch and try to improve it further by adding patches, once you have something working I might consider merging but right now I already spent too much time on this :wink:

**Comment by conao3** [comment]
I am sorry I let you use your time due to this issue. I am also working on this, but there is no good news...

**Comment by conao3** [comment]
I will work till next week, but if I still can not achieve it I will give up and close this issue.

**Comment by Silex** [comment]
No worries it was somewhat interesting to debug this using git bisect.

Anyway, maybe for this particular usecase you could create your `22` container another way: by copying the system's emacs binary & dependencies in some OSXish image. That or just `-v /usr/bin` or some other trick, so your test suite uses docker for all versions except it gets some kind of fake image that does the job just for version < 23.4.

**Comment by conao3** [comment]
It seems that Emacs-22 is already difficult to build on Docker and on Linux, so that approach may be correct.
However, in order to run OSX Emacs-22 at `/usr/local/emacs` , I think it is necessary to run the Mach-O execution binary on Docker, is it possible?

below libraries are `/user/bin/emacs` 's dependency
```
$ otool -L /usr/bin/emacs                                                                                                                                                                           
/usr/bin/emacs:
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

**Comment by Silex** [comment]
Well yeah, you'll need to figure how to copy or mount all the dependencies, and also check wether it's feasible at all. Doesn't docker on OSX run in a virtual machine? If that's the case I don't think you can actually do it given you don't share the same kernel.

**Comment by conao3** [comment]
In Travis-CI? VM used on Travis-CI can run OSX. https://docs.travis-ci.com/user/reference/overview/
hmm. I try again...

**Comment by conao3** [comment]
Time’s up. I give up the image and drop Emacs-22 for packages I develop.
