### ISSUE TITLE
Clarify what license this project

### ISSUE THREAD

**Issue by conao3** [Silex/docker-emacs#42]
Hello,

I'd like to use your code with a bit change for me.
Could you clarify what license this project is open to?

**Comment by Silex** [comment]
Good question! Hum, probably some kind of BSD-like license, but I need to think about it. Will add a license next week.

**Comment by conao3** [comment]
OK, Thanks!

**Comment by Silex** [comment]
Done, licensed it GPL v3 for the time being.

**Comment by conao3** [comment]
OK! I will open my Fork under the save GPL v3 as this project.
