### ISSUE TITLE
Add --with-modules to dev containers

### ISSUE THREAD

**Issue by justinbarclay** [Silex/docker-emacs#46]
Hey, 

Just want to say I really like what you've done here. This is a really slick project.

I was wondering if you would be willing to add the --with-modules flag to your docker containers for emacs 25+? I'd like to use your containers when I run the CI/CD for a package I'm creating that requires the use of dynamic modules. If that doesn't work for you I understand, I just thought it would be better than me maintaining my own poor copies of your Dockerfiles. 😊

Cheers,

Justin

**Comment by Silex** [comment]
Good idea, let's continue in #47
