### ISSUE TITLE
Require spell checker

### ISSUE THREAD

**Issue by tesujimath** [Silex/docker-emacs#5]
Currently flyspell barfs, not finding ispell.  Could ispell or equivalent be added to the container, please?

**Comment by Silex** [comment]
Good idea! Will do it tomorrow, ping me if I forget

**Comment by tesujimath** [comment]
Great, thanks!

**Comment by Silex** [comment]
Alright, done in https://github.com/Silex/docker-emacs/commit/7ee44cf8e94e55c286f339ca69303236afd8dd2c

**Comment by tesujimath** [comment]
This is perfect, thanks!

**Comment by Silex** [comment]
@tesujimath: in `alpine` there's no ispell. There is `aspell` or `hunspell`. Is that worth adding to the image?

My understanding is that `aspell` requires additional configuration so there's little use in adding it to the alpine image, if one has to configure he can also `apk add --no-cache aspell`.

**Comment by tesujimath** [comment]
I think aspell would be useful. Isn't the configuration you mention emacs configuration, so not done inside the container, but in .emacs?

**Comment by Silex** [comment]
> Isn't the configuration you mention emacs configuration, so not done inside the container, but in .emacs?

Yes, it is. Okay I've added aspell, and Emacs automatically detects it!

**Comment by tesujimath** [comment]
Great, thanks!
