### ISSUE TITLE
Add support for `docker stats`

### ISSUE THREAD

**Issue by dcaixinha** [Silex/docker-emacs#50]
Hey @Silex, first of all, thank you for all the great work with this package :raised_hands: 

One thing that I recently felt missing from my non-emacs Docker workflow, is the ability to check the stats for each container (running the command [docker stats](https://docs.docker.com/engine/reference/commandline/stats/). This is particularly helpful when a `docker-compose up` takes a long time, as I can create a buffer to check the CPU and MEM usage of all containers, and realize when they're done booting up.

Do you think this would be possible to add to `docker.el`? Thanks :pray:

**Comment by Silex** [comment]
It sounds like a good idea, but I have trouble finding time to work on docker.el :cry: 

I'll keep this open, maybe someone could volunteer. Ideally, I see something that inherits from `proced` maybe.

**Comment by dcaixinha** [comment]
Hey @Silex, I just realized now that I've opened this in the wrong repo :disappointed: I meant to open it in [docker.el](https://github.com/Silex/docker.el). Should I open it there? Either way, I can try to take a look at it, although I'm still quite a noob in Emacs Lisp.

In my (probably naive) view, I would do something similar to `docker-containers` but running `docker stats` as the feeding command (and possibly displaying info in a different way). What do you think?

**Comment by Silex** [comment]
Heh, I didn't realize either :rofl: 

Yeah open it in docker.el and we'll continue discussing there.
