### ISSUE TITLE
Include Source Code Pro font for better Spacemacs experience

### ISSUE THREAD

**Issue by tesujimath** [Silex/docker-emacs#6]
I'm just investigating using this container to run [Spacemacs](https://github.com/syl20bnr/spacemacs).

It all seems OK, but it would be nice if the container included the [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) font, for a better out-of-the-box experience with Spacemacs.

**Comment by Silex** [comment]
Hum, how about using a custom Dockerfile for that? Something like

``` Dockerfile
FROM silex/emacs:latest
RUN (install font instructions)
```

Installing a font looks really "user" specific so I think it's better left as a customization.

**Comment by tesujimath** [comment]
Ah, OK, that sounds reasonable.  Thanks for the hint.
