### ISSUE TITLE
Emacs 27 has a portable dumper

### ISSUE THREAD

**Issue by lassik** [Silex/docker-emacs#65]
FYI, from the [27.1 release announcement](https://lists.gnu.org/archive/html/emacs-devel/2020-08/msg00237.html):

> Emacs 27.1 has a wide variety of new features, including:
>
> - Portable dumping used instead of unexec

I just verified that building it from source works when running Docker on an ASLR-enabled Linux kernel.

**Comment by Silex** [comment]
@lassik: yes I know, you can get a bit of history about that at https://github.com/moby/moby/issues/22801 (I created the issue :wink:)

Still the older images needs to be built with ASLR disabled.
