### ISSUE TITLE
Latest base image

### ISSUE THREAD

**Issue by baracunatana** [Silex/docker-emacs#66]
Would there be any advantage in basing the docker-emacs images on the latest ubuntu/alpine versions? Just wondering if it is worthy to invest some time on that.

**Comment by Silex** [comment]
Well, _"it depends"_.

Emacs is a software that always built against what was the current version of libraries at the time. So if you want to build say Emacs 25.2 on Ubuntu 20.04, you have to _downgrade_  a lot of libraries for it to actually build.

At the moment, everything < 24.5 is built with 14.04, and everything >= 24.5 is built with 18.04.

I expect that everything > 26.1 would build with 20.04, but I'm not sure.

Also, latest alpine has very few packages compared to previous versions. For example I simply bumped to alpine 3.10 to test and a lot of images didn't build, even tho these alpine are very similar.

So, in theory yes there is interest to always build on the latest image possible, in practice it's a lot of try & err in figuring out which lib version is required etc. But that'd require quite some refactoring to move from `apt get install foo` into `wget foo && tar -x && make install`.

**Comment by Silex** [comment]
@juanerasmoe: so basically the answer is yes, I'm interested in the latest base image, but I don't have time to investigate the dependency hell. If you can help with that leave the issue open and comment your findings, if not just close the issue :wink:

**Comment by Silex** [comment]
The latest images are based on `alpine:latest` and `debian:latest` 🎉
