### ISSUE TITLE
Alpine 3.12

### ISSUE THREAD

**Issue by Silex** [Silex/docker-emacs#67]
@sirikid: can you help with alpine 3.12 failing? See https://gitlab.com/Silex777/docker-emacs/-/jobs/732869952 (timeout), you can try to build the dockerfile yourself at https://github.com/Silex/docker-emacs/blob/alpine312/26.3/alpine/3.12/dev/Dockerfile I tried following https://github.com/alpinelinux/aports/blob/3.12-stable/community/emacs/APKBUILD

When I try on my computer the same happens. Don't forget to `sudo sysctl kernel.randomize_va_space=0` :wink:

**Comment by sirikid** [comment]
Ok, I will take a look at it in a few days

**Comment by sirikid** [comment]
Well, I had [another error](https://termbin.com/00a5). Have you ever seen it before? The log is slightly corrupted because I ran the build in eshell. I also used podman.

**Comment by Silex** [comment]
> Don't forget to `sudo sysctl kernel.randomize_va_space=0`

Do that and it'll build.

If you are interested: https://github.com/moby/moby/issues/22801

**Comment by Silex** [comment]
You can also test https://github.com/Silex/docker-emacs/blob/alpine312/27.1/alpine/3.12/dev/Dockerfile which doesn't require the `randomize_va_space` trick (27.1 introduced the portable dumper). Note that this Dockerfile builds the simplest way possible (no fancy CFLAGS like alpine does).

**Comment by Silex** [comment]
Ok thanks to https://git.alpinelinux.org/aports/plain/community/emacs/no-git-repo.patch I was able to find it's git that hangs.

The patch does not work but uninstalling git before building seems to work... for a while but then it hangs later on again :sweat_smile:

**Comment by Silex** [comment]
The latest images are based on `alpine:latest` and `debian:latest` 🎉
