### ISSUE TITLE
Build Emacs 26.0.91?

### ISSUE THREAD

**Issue by gonewest818** [Silex/docker-emacs#7]
I think the images being pushed to dockerhub these days are 24.5, 25.1, 25.2, 25.3, and 27.0.x. 

Because Emacs "master" has [advanced to 27.x](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=977cd6cb28a37744966ec62f70cf62659f6f302a), and the Emacs 26 pre-releases are now on [branches numbered like "emacs-26.0.91"](http://git.savannah.gnu.org/cgit/emacs.git/tag/?h=emacs-26.0.91).

**Comment by Silex** [comment]
Good idea. Will try to do it tomorrow.

**Comment by gonewest818** [comment]
actually, I can send a pull request in a few minutes. I was just looking at multi-stage builds to make the images a little smaller (without the compiler toolchain) but it doesn't really save much.

Do you have a preference for the tags? 
Something along the lines of `DOCKER_TAGS="26.0 26 pretest"` ?

**Comment by Silex** [comment]
:+1:  we'll continue the discussion in #8
