### ISSUE TITLE
Emacs-24.4 fail TLS handshake

### ISSUE THREAD

**Issue by conao3** [Silex/docker-emacs#72]
Thanks for maintaining docker-emacs!

I found silex/emacs:24.4 image could not install any package from MELPA.

```
$ docker run -it --rm silex/emacs:24.4 bash
root@d3720e52c348:/# emacs --batch -Q --eval "(progn (setq package-archives '((\"gnu\" . \"https://elpa.gnu.org/packages/\") (\"melpa\" . \"https://melpa.org/packages/\"))) (package-initialize) (package-refresh-contents) (package-install 'ansi))"
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
gnutls.c: [0] (Emacs) fatal error: A TLS fatal alert has been received.
gnutls.c: [0] (Emacs) Received alert:  Handshake failed
gnutls.el: (err=[-12] A TLS fatal alert has been received.) boot: (:priority NORMAL :hostname melpa.org :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Failed to download `melpa' archive.
Package `ansi-' is unavailable
```

But Purcell's [nix-emacs:24.4 can install package](https://github.com/cask/cask/runs/1859384672#step:6:40) from MELPA. Maybe one of [patch](https://github.com/purcell/nix-emacs-ci/tree/master/patches) is needed...?

@purcell, any suggestions?

---
### Note
silex/emacs:24.5 could install package from MELPA.
```
$ docker run -it --rm silex/emacs:24.5 bash
root@55596af4814a:/# emacs --batch -Q --eval "(progn (setq package-archives '((\"gnu\" . \"https://elpa.gnu.org/packages/\") (\"melpa\" . \"https://melpa.org/packages/\"))) (package-initialize) (package-refresh-contents) (package-install 'ansi))"
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Contacting host: melpa.org:443
Parsing tar file...
Parsing tar file...done
Extracting dash-20210202.1153/
Extracting dash-20210202.1153/dash.info
Wrote /root/.emacs.d/elpa/dash-20210202.1153/dash.info
Extracting dash-20210202.1153/dash.el
Wrote /root/.emacs.d/elpa/dash-20210202.1153/dash.el
...
```

**Comment by purcell** [comment]
> Maybe one of [patch](https://github.com/purcell/nix-emacs-ci/tree/master/patches) is needed...?

Yes, probably the eagain patch.

**Comment by Silex** [comment]
Thanks, I'll try purcell's patch.

**Comment by Silex** [comment]
I really wish I could delegate the emacs building to https://github.com/purcell/nix-emacs-ci and just focus on the docker images part.

I started investigating in https://github.com/purcell/nix-emacs-ci/issues/29 but I have no time 😢 I'm a new father and well priorities changed 😄 

I think I'll start looking for maintainers for my projects, including this one.

**Comment by conao3** [comment]
> I really wish I could delegate the emacs building to https://github.com/purcell/nix-emacs-ci and just focus on the docker images part.

Yes, I think so too.

> I started investigating in purcell/nix-emacs-ci#29 but I have no time cry I'm a new father and well priorities changed smile
> I think I'll start looking for maintainers for my projects, including this one.

Very good news! If you need help, please let me know at any time.

**Comment by Silex** [comment]
> Very good news! If you need help, please let me know at any time.

Oh, yes I do 😄 I added you as a collaborator.

How should I contact you? email? We need to discuss architecture/hardware etc. I'm currently building the images on gitlab using an arm32/64 private server borrowed from packet.com and the usual gitlab workers for the i386/x64 images.

Moving to purcell's nix would probably mean we use it to help build the arm versions of the nix packages and for the docker images we can use something simpler like travis.

**Comment by conao3** [comment]
Thanks, but I'm busy too hunting for a new job, I cant take a lot of time on this project... Anyway, I try it.

> How should I contact you? email? We need to discuss architecture/hardware etc. I'm currently building the images on gitlab using an arm32/64 private server borrowed from packet.com and the usual gitlab workers for the i386/x64 images.

> Moving to purcell's nix would probably mean we use it to help build the arm versions of the nix packages and for the docker images we can use something simpler like travis.

I want to use GitHub issue board #73.

**Comment by Silex** [comment]
Should be fixed wiht the latest images.
