### ISSUE TITLE
url-retrieve-synchronously broken on 25-alpine?

### ISSUE THREAD

**Issue by sulami** [Silex/docker-emacs#75]
I've noticed that on recent CI runs, I run the same suite for 25-, 26- and 27-alpine images, and 25-alpine just started hanging some time within the last few days.

At a first glance it seems to be `url-retrieve-synchronously` from [the straight bootstrapping](https://github.com/sulami/literate-calc-mode.el/blob/master/test/deps.el#L31).

I'm not sure what exactly I could poke at, but I'm happy to assist in further debugging if I can be of any help.

**Comment by Silex** [comment]
Hello,

Yes, alpine images are semi-broken (https://github.com/Silex/docker-emacs/issues/69). Some of them seems to "work" tho.

Given all the issues I have with alpine images and building Emacs in general my goal is to try to move to purcell's nix packages (https://github.com/purcell/nix-emacs-ci/issues/29), so you can help with that :wink:

**Comment by sulami** [comment]
> Yes, alpine images are semi-broken
> (https://github.com/Silex/docker-emacs/issues/69). Some of them are
> some of them "work".

Ah well, didn't see that.

> Given all the issues I have with alpine images and building Emacs in
> general my goal is to try to move to purcell's nix packages
> (https://github.com/purcell/nix-emacs-ci/issues/29), so you can help
> with that :wink:

Great, I didn't even know this existed, but it scratches all my itches
at once. I'll have a look at that once I get some time.

**Comment by Silex** [comment]
Should be fixed with the latest images, please reopen if it doesn't.
