### ISSUE TITLE
How to install packages?

### ISSUE THREAD

**Issue by dereisele** [Silex/docker-emacs#77]
Hello,

I want to use this image to export org-mode documents to latex in a GitLab CI pipeline.
The problem I need org-ref, but I have no I idea of how to install it using the command line.
I would appreciate if someone could give me a hint, but I would accept if this issue is out of scope. 

I case your wondering, I'm using Spacemacs locally and the CI stuff is based on [doc-org](https://github.com/doc-org/doc-org).

**Comment by maurelio1234** [comment]
Just create a init.el file on the image and it will run when you start emacs.
In the init.ele just install org-ref, it will be installed when you run emacs.

**Comment by dereisele** [comment]
Thank you very much. I wasn't aware that the M-x commands are regular function calls like in the init.el .
I found a installation guide at [https://orgmode.org/elpa.html](https://orgmode.org/elpa.html).
Here is the start of my init.el for reference: 
```
(require 'package)
(add-to-list 'package-archives
 '("melpa" . "http://melpa.org/packages/") t)

(unless package-archive-contents    ;; Refresh the packages descriptions
  (package-refresh-contents))
(setq package-load-list '(all))     ;; List of packages to load
(unless (package-installed-p 'org)  ;; Make sure the Org package is
  (package-install 'org))           ;; installed, install it if not
(unless (package-installed-p 'org-ref)  ;; Make sure the Org-Ref package is
  (package-install 'org-ref))           ;; installed, install it if not
(package-initialize)                ;; Initialize & Install Package

(require 'org-ref)

;; org-mode config
(setq org-latex-compiler "xelatex")
;; ... 
```

**Comment by maurelio1234** [comment]
Yes, AFAIK org is not part of emacs, so you will have at least the latest version from the release you are running, so no need to install it again.
