### ISSUE TITLE
M-x not working in gui

### ISSUE THREAD

**Issue by jkitchin** [Silex/docker-emacs#82]
Thanks for sharing this work! I am running a gui version like this on a Mac

```
xhost + 127.0.0.1
docker run -ti --rm --name semacs  -e DISPLAY=host.docker.internal:0 silex/emacs
```

It works, but I cannot use M-x, it inserts ≈ instead. Is this something I need to fix on the docker side, or something on the MacOS side?

It works fine if I use ESC-x to run commands, just not with M-x.

Interestingly, it seems like command-x is mapped to M-x.

**Comment by Silex** [comment]
This looks like a MacOS problem, try solving with https://www.emacswiki.org/emacs/MetaKeyProblems#h5o-15

**Comment by jkitchin** [comment]
that does sound like the issue. Thanks for the link. The obvious thing in the XQuartz settings doesn't seem to fix it. I will do some more digging and post a solution when I find one.

**Comment by jkitchin** [comment]
I have found a potential solution. I don't know if it is a general solution, but here is what works for me. 

I was not able to get XQuartz to stop hijacking the Alt, although you can set Option keys to send Alt_L, Alt_R, and then run emacs with 

CMD ["emacs", "--eval=(setq x-alt-keysym 'meta)"]

I like this solution better though, because it matches my super/hyper arrangement in my usual setup.

Make an xmodmap file with these contents:

```
! undo any modifiers set
clear mod1
clear mod2
clear mod3

! keycodes 66 and 69 are the option/alt keys
keycode 66 = Meta_L
keycode 69 = Meta_R

keycode 63 = Super_L
keycode 71 = Hyper_R

add mod1 = Meta_L Meta_R
add mod2 = Super_L
add mod3 = Hyper_R
```

Use this Dockerfile (adds xev and xmodmap, and modifies the keyboard map):

```
FROM silex/nix

ADD https://api.github.com/repos/Silex/nix-emacs-ci/commits?per_page=1 /tmp/cache
RUN nix-env -iA emacs-27-2 -f https://github.com/silex/nix-emacs-ci/archive/master.tar.gz
RUN nix copy --no-require-sigs --to /nix-emacs $(type -p emacs)
RUN cd /nix-emacs/nix/store && ln -s *emacs* emacs

FROM alpine:3.14

RUN apk add --no-cache \
            curl \
            gnupg \
            openssh-client \
            xev xmodmap

COPY --from=0 /nix-emacs/nix/store /nix/store
ENV PATH="/nix/store/emacs/bin:$PATH"

COPY xmodmap ~/.xmodmap
RUN echo "xmodmap ~/.xmodmap" > ~/.xinitrc

CMD ["emacs"]
```

This seems to do exactly what I want. 

I will close the issue, since it doesn't seem to be an issue with the repo, but maybe this solution will be helpful (probably to future me when I search for it again!) to someone.
