### ISSUE TITLE
Successive builds create distinct image hashes

### ISSUE THREAD

**Issue by gonewest818** [Silex/docker-emacs#9]
I'm in the process of changing the elisp projects I work on from Travis CI to CircleCI. I'm using these docker images as the basis for the CircleCI jobs. I'm assuming CircleCI must cache docker images to accelerate the launch of jobs using a common docker image.

However, I am pretty sure what I'm seeing is each of your daily docker-emacs builds produces a new set of docker images with different hashes even when the Emacs sources didn't change. And I know Emacs releases like 24.x and 25.x don't change. Even a critical security update would produce a new point release, or a new major one.

I have an approach for this in mind. Should be able to fetch the Emacs sources first, and `COPY` into the build context in such a way that `docker build`'s own mechanisms can determine if they are the same fileset as the previous daily build.

**Comment by Silex** [comment]
> However, I am pretty sure what I'm seeing is each of your daily docker-emacs builds produces a new set of docker images with different hashes even when the Emacs sources didn't change. And I know Emacs releases like 24.x and 25.x don't change. Even a critical security update would produce a new point release, or a new major one.

Yes, I know about this problem. I've tried to fix it some while ago but the obvious fix did not work.

> I have an approach for this in mind. Should be able to fetch the Emacs sources first, and COPY into the build context in such a way that docker build's own mechanisms can determine if they are the same fileset as the previous daily build.

Well that is the problem, the docker build cache is not reused between image builds. I've tried pulling the existing image first in order for the build to avoid re-building uncesseray layers, but I believe that only works if you reuse the build cache between runs. That would mean somehow cache `/var/lib/docker` between runs.

If you have an idea to fix this it'd be very welcome, I'm not sure your `COPY` idea would work tho.

The obvious fix would be to stop using travis-ci and have a box that simply builds the images every hours or so and then push them, and the docker cache would avoid uncessary builds/pushes.

**Comment by gonewest818** [comment]
Well, from what I've seen it would be done like
```
docker pull <previous-image>
docker build --cache-from <previous-image> ...
```

That's what I'm going to try.

**Comment by Silex** [comment]
Ah ah! I didn't know about `--cache-from`.

It sounds promising, keep me updated :smile:

**Comment by gonewest818** [comment]
That works.  Here's the transcript of a repeat build of "master", elapsed time 1:54.

The build is completely cached.

<img width="907" alt="screen shot 2018-02-20 at 4 56 29 pm" src="https://user-images.githubusercontent.com/2460918/36457536-5e98c30e-165f-11e8-94d7-5dee1bedf6c3.png">

The push is also a no-op because the image hasn't changed.

<img width="902" alt="screen shot 2018-02-20 at 4 56 57 pm" src="https://user-images.githubusercontent.com/2460918/36457547-6703a2e8-165f-11e8-97cb-56c1aaeec571.png">

**Comment by gonewest818** [comment]
I have a pull request for this too, but it extends from #11, so when you merge #11 I can rebase and submit the other PR. The commit is https://github.com/gonewest818/docker-emacs/commit/b09cf30502d0b65611c81aac81484c8d34f027e8

**Comment by Silex** [comment]
Alright, you can make the new PR :-)

**Comment by Silex** [comment]
Ok this has resurfaced... and the error is kinda obvious: it does not make sense for multistage images to be used as `--cache-from` (otherwise the previous stage would be part of the image).

So basically right now the `-dev` image are built "when needed" (like expected), and the others are built all the time. Looks like I will have to resurrect my `depends:` idea :smile: 

This is a silly mistake on my part, I'll try to solve it soon, in the meantime I changed the builds to once per week to mitigate the issue.

**Comment by Silex** [comment]
Ok this should be fixed on master by caching the docker layers.

This is not really ideal so I have another branch brewing where the build is entirely ruby-based, and where "stage 0" (dev) images will be pushed to the registry. That means we'll get unadvertised `alpine-dev` images :-)

**Comment by Silex** [comment]
Note for future readers: the docker layers are not cached anymore with the recent changes, we simply use `--cache-from` with the pulled images.
