### ISSUE TITLE
`master` image is apparently not updated

### ISSUE THREAD

**Issue by doublep** [Silex/docker-emacs#90]
Some history: I received a bug report https://github.com/doublep/eldev/issues/76. I then tracked it down to a bug in Emacs that caused installed packaged to be non-byte-compiled (at least for the installing instance). I managed to reproduce it with this:

    cat >does-install-byte-compile.el <<EOF
    (setf package-user-dir (make-temp-file "emacs-packages" t))
    (require 'package)
    (package-initialize t)
    (package-install 'dash)
    (message "%S" (byte-code-function-p (symbol-function '-each)))
    (unless (byte-code-function-p (symbol-function '-each))
      (report-emacs-bug "XXX")
      (message "\n%s" (buffer-string)))
    EOF

    emacs --batch --load does-install-byte-compile.el

When not buggy, the output should end in `Package ‘dash’ installed. t`. When buggy — print `report-emacs-bug` information.

With image `silex/emacs:master` the bug still happens. I made sure to run `docker pull` first:

    $ docker pull silex/emacs:master; docker run -it silex/emacs:master /bin/bash

But the bug is apparently fixed in Emacs `master` long time ago.

The binary in the image suggest it has been built from a *March* commit:

    In GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
    System Description: Debian GNU/Linux 11 (bullseye)

    Configured using:
     'configure
     --prefix=/nix/store/fam04cbjqrwhvzg2j35pabikpgf0a9k1-emacs-snapshot-a1fa3d24
     --disable-build-details --with-modules'

where:

    commit a1fa3d24d7f96542530f30c28daf9bf8aaaeae13
    Author: Po Lu <luangruo@yahoo.com>
    Date:   2022-03-14 06:48:34 +0000

**Comment by Silex** [comment]
Saw you found #86, so closing this.

**Comment by doublep** [comment]
How is it the same? That bug is about how to find the revision, this one is about *image being almost half a year old*.

**Comment by Silex** [comment]
Well in the linked issue you see it's in @purcell's hands, tho I realise it's my fault because I forgot to update my fork. This should be fixed in the next build.

**Comment by doublep** [comment]
Then you need to add a GitHub workflow to do this automatically or at least remind you if there are unmerged news. Otherwise you will forget again soon.
