### ISSUE TITLE
silex/emacs:28.2-alpine-dev alternative

### ISSUE THREAD

**Issue by batrov** [Silex/docker-emacs#93]
I was using silex/emacs:28.2-alpine-dev image and per https://github.com/Silex/docker-emacs/commit/0ed90373448d41826ae9f1c0917efbc8f95ac189 seems dev image is deleted. Which image should I use as alternative?

**Comment by Silex** [comment]
Hello!

Well, probably `28.2-alpine-ci` ?

What tools are you missing from this image, maybe I can add them?

**Comment by batrov** [comment]
Thank you, using `alpine-ci` works like charms.

We were using `make markdown` script.

**Comment by Silex** [comment]
Perfect, the image is also much smaller :+1:
