### ISSUE TITLE
Please add 27.1 (default emacs version on Ubuntu and Debian Stable)

### ISSUE THREAD

**Issue by Trevoke** [Silex/docker-emacs#94]
The tool I use for TDD relies on your docker images to provide testability across different emacs versions, and it's a shame that this version is missing since it is the version available on Ubuntu and Debian stable.

**Comment by Silex** [comment]
Hum. I dropped support for the non-latest images of each major version a while ago in https://github.com/Silex/docker-emacs/issues/62#issuecomment-810532699

This follows the convention used by docker images for languages like Ruby etc.

Of course it's not much work to reintroduce non-latest versions but then there is so much images, it's basically almost triple the current amount of images (see https://github.com/Silex/docker-emacs#tags).

Maybe what can be done is only add 27.1 because it scratches your itch and not reintroduce all the other ones.

**Comment by Trevoke** [comment]
I think there's two things here.

First, it's a weird dance of dependencies: eldev has a plugin/extension which allows for testing inside docker containers, and that extension by default depends on your images, which means the path of least resistance does not include 27.1 - I have since figured out that I could use podman to build local container images and test them, so technically this is no longer a blocker for me.

However, since you mentioned "support for the non-latest images of each major version", then we should ask about the real purpose of these images and containers you provide, because my assumption may be incorrect, and this is the second thing.

So, "latest" is interesting, especially in the Linux world, because we have Debian, which is supposed to be so stable it'll keep running without power and after a nuclear strike take out half the motherboard, and we have things like Nix which allow you to build from source without batting an eyelid. And I had assumed that because you had dropped support for 27.1 meant that I no longer had to support 27.1 in my package, but that was incorrect! Because it turns out that YOU dropped support for Debian and Ubuntu, not that Debian and Ubuntu upgraded from 27.1 ! 

So, if your goal is to only provide the two most recent versions of emacs, and that's it, regardless of what the distributions do, then you should not add 27.1, and it just means that people who want to support Ubuntu and Debian need to use another tool -- and that is your decision as the provider and maintainer of the tool!

I would argue, however, that matching docker containers for programming languages is not necessarily a clear use-case parallel. As a developer, I use a variety of version managers -- the distribution/operating system I use is almost more an inconvenience than anything else. For emacs users, emacs HAS TO WORK.

**Comment by Silex** [comment]
Hum.

The more I think about it the more it makes sense to have a lot of images so testing is easy.

At the beggining this project was to run GUI emacs, nowadays it evolved toward testing.

So, I'll restore many images soon and probably rework how the README is displayed.

**Comment by Silex** [comment]
Closed by a7c96ef
