### ISSUE TITLE
Support Eask?

### ISSUE THREAD

**Issue by jcs090218** [Silex/docker-emacs#96]
Hi, I am the author of [Eask](https://github.com/emacs-eask/cli). I wonder if it's possible for this repo to support Eask as well? 🤔 

Some information about Eask, see https://www.reddit.com/r/emacs/comments/12bbjew/eask_v08x_released/.

Thanks!

**Comment by Silex** [comment]
Hum, in theory yes but in practice I have to consider a few things:

- what is the range of supported Emacs version?
- will eask replace cask eventually or do you see them as living their own life for a long time?

**Comment by jcs090218** [comment]
Thanks for the reply!

> * what is the range of supported Emacs version?

Eask support 26.1 or above.

> * will eask replace cask eventually or do you see them as living their own life for a long time?

Eask is much more powerful than Cask now, so Cask can totally be replaced by Eask. Eask will continue to grow since it uses much more mature technology, so it's pretty easy to expand and maintain. In the long run, I hope it will have its own ecosystem.

**Comment by Silex** [comment]
>> * will eask replace cask eventually or do you see them as living their own life for a long time?
 
> Eask is much more powerful than Cask now, so Cask can totally be replaced by Eask. Eask will continue to grow since it uses much more mature technology, so it's pretty easy to expand and maintain. In the long run, I hope it will have its own ecosystem.

My question was more if Cask is on a dying path and we could replace the -cask images by -eask. I have no clue I don't use these tools 😅

**Comment by jcs090218** [comment]
> My question was more if Cask is on a dying path and we could replace the -cask images by -eask. I have no clue I don't use these tools 😅

I think it's better to keep Cask for now since there are people who still use Cask. WDYT? 🤔

**Comment by Silex** [comment]
Yeah. Adding a 4th ci tool will probably require me to refactor the tool first so adding variants is easier.

I plan on using a ci-matrix instead of the current setup which was necessary back when everything was built differently.

So it might take a while before I start addressing this issue 😅 

Just pasting the install command here so I have the necessary infos when I come back to this issue 😉 

```
curl -fsSL https://raw.githubusercontent.com/emacs-eask/cli/master/webinstall/install.sh | sh
```

**Comment by jcs090218** [comment]
> So it might take a while before I start addressing this issue 😅

No problem! I appreciate your hard work in making the Emacs ecosystem better! ❤️ 🚀

**Comment by Silex** [comment]
It's done, please test the images & report if anything bugs.

**Comment by jcs090218** [comment]
Wow, that's faster than I expected! Thank you so much! 🚀 

> It's done, please test the images & report if anything bugs.

100%, will do! ❤️
