### ISSUE TITLE
`wget` support

### ISSUE THREAD

**Issue by vemv** [Silex/docker-emacs#99]
Hi!

Would you generously add `wget` to this image?

That way we (at CIDER) could easily add `shellcheck` to our CI builds.

We currently use `silex/emacs:28-ci`.

Thanks - V

**Comment by Silex** [comment]
Ah yes, thought it'd be there already but it's only curl.

**Comment by vemv** [comment]
Hey, sorry, I forgot about this one - should have closed it.

Even after installing wget, I faced problems with shellcheck, so it became evident at that point that using a dedicated docker image just for shellcheck was the way to go.

**Comment by Silex** [comment]
Done in https://github.com/Silex/docker-emacs/commit/84d878c5c41878d8ef14754cbe2cd8a168164ff7
